# Generated by Django 5.2 on 2025-06-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='id_proofs/'),
        ),
    ]
